// Generated by CoffeeScript 1.6.3
(function() {
  var $, Overlay, Q;

  $ = window.jQuery || require('jquery');

  Q = require('q');

  Overlay = (function() {
    function Overlay() {}

    Overlay.visible = false;

    Overlay.color = 'black';

    Overlay.opacity = 0.8;

    Overlay.zIndex = 1000;

    Overlay.duration = 'fast';

    Overlay.scrollable = false;

    Overlay.el = null;

    Overlay.events = {
      show: [],
      shown: [],
      hide: [],
      hidden: []
    };

    Overlay.show = function(options) {
      var deferred,
        _this = this;
      if (options == null) {
        options = {};
      }
      deferred = Q.defer();
      if (typeof options.color === 'undefined') {
        options.color = this.color;
      }
      if (typeof options.opacity === 'undefined') {
        options.opacity = this.opacity;
      }
      if (typeof options.zIndex === 'undefined') {
        options.zIndex = this.zIndex;
      }
      if (typeof options.duration === 'undefined') {
        options.duration = this.duration;
      }
      if (typeof options.scrollable === 'undefined') {
        options.scrollable = this.scrollable;
      }
      if (this.visible === false) {
        this.callEvent('show');
        if (options.scrollable === false) {
          $('body').css('overflow', 'hidden');
        }
        if (this.el === null) {
          this.el = $('<div>', {
            css: {
              display: 'none',
              position: 'fixed',
              left: 0,
              top: 0,
              width: $(window).width(),
              height: $(window).height()
            },
            click: function(e) {
              return _this.hide();
            }
          }).appendTo($('body'));
        }
        $(window).on('resize.overlay', function(e) {
          return _this.onResize();
        });
        this.el.css({
          backgroundColor: options.color,
          opacity: options.opacity,
          zIndex: options.zIndex
        });
        this.el.fadeIn(options.duration, function() {
          _this.visible = true;
          deferred.resolve(_this);
          return _this.callEvent('shown');
        });
      } else {
        deferred.reject(new Error('Overlay is already visible'));
      }
      return deferred.promise;
    };

    Overlay.onResize = function() {
      if (this.visible === true) {
        return this.el.css({
          width: $(window).width(),
          height: $(window).height()
        });
      }
    };

    Overlay.hide = function() {
      var deferred,
        _this = this;
      deferred = Q.defer();
      if (this.visible === true) {
        this.callEvent('hide');
        this.el.fadeOut(this.duration, function() {
          _this.visible = false;
          deferred.resolve(_this);
          return _this.callEvent('hidden');
        });
        $(window).off('resize.overlay');
        if (this.scrollable === false) {
          $('body').css('overflow', 'visible');
        }
      } else {
        deferred.reject(new Error('Overlay is not visible'));
      }
      return deferred.promise;
    };

    Overlay.on = function(event, fn) {
      return this.events[event].push(fn);
    };

    Overlay.callEvent = function(name) {
      var event, _i, _len, _ref, _results;
      _ref = this.events[name];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        event = _ref[_i];
        _results.push(event.call(this));
      }
      return _results;
    };

    return Overlay;

  })();

  module.exports = Overlay;

}).call(this);
